FROM python:2.7.13
MAINTAINER Narasa Kumar "knarasa@gmail.com"
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python","app.py"]
#Sample URL is https://github.com/sithu/assignment1-config-example
CMD ["url"]
